# Building Image
name: Publish JupyterLab Image 

on:
  push:
    branches:
      - main
  release:
    types: [published]
    
jobs:
  push_to_registry:
    name: Push Docker JupyterLab Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      
      - name: Build and push Docker JupyterLab-Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/docker/jupyterlab/Dockerfile
          push: true
          tags: padzx/jupyter_lab:latest

      - name: Extract metadata for Docker JupyerLab-Image
        id: meta_jupyterlab
        uses: docker/metadata-action@v2
        with:
          images: padzx/jupyter_lab
