name: Publish PostgreSQL Image 

on:
  push:
    branches:
      - main
  release:
    types: [published]
    
jobs:
  push_to_registry:
    name: Push Docker PostgreSQL Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      
      - name: Build and push Docker PostgreSQL-Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/docker/postgresql/Dockerfile
          push: true
          tags: padzx/postgresql:latest

      - name: Extract metadata for Docker Postgresql-Image
        id: meta_postgresql
        uses: docker/metadata-action@v2
        with:
          images: padzx/postgresql